# Controllers for Professor Robot in Gazebo
professor_robot:
  # Joint State Controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Individual wheel controllers
  wheel_rear_left_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_base_wheel_rear_left
    pid: { p: 100.0, i: 0.01, d: 10.0 }

  wheel_rear_right_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_base_wheel_rear_right
    pid: { p: 100.0, i: 0.01, d: 10.0 }

  wheel_front_left_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_base_wheel_front_left
    pid: { p: 100.0, i: 0.01, d: 10.0 }

  wheel_front_right_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_base_wheel_front_right
    pid: { p: 100.0, i: 0.01, d: 10.0 }

  # Differential drive controller (recommended)
  diff_drive_controller:
    type: diff_drive_controller/DiffDriveController
    left_wheel: "joint_base_wheel_rear_left"
    right_wheel: "joint_base_wheel_rear_right"
    publish_rate: 50.0
    pose_covariance_diagonal:
      [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal:
      [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    # Robot physical properties
    wheel_separation: 0.324 # Distance between wheels (adjust based on your robot)
    wheel_radius: 0.16 # Wheel radius from URDF

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 2.0 # m/s
        min_velocity: -2.0 # m/s
        has_acceleration_limits: true
        max_acceleration: 1.0 # m/s^2
        min_acceleration: -1.0 # m/s^2
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.5 # rad/s
        min_velocity: -1.5 # rad/s
        has_acceleration_limits: true
        max_acceleration: 1.0 # rad/s^2
        min_acceleration: -1.0 # rad/s^2

    # Topic remapping
    cmd_vel_timeout: 0.5
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
