# Clean Costmap Common Parameters
# Based on proven ROS navigation tutorial configurations
# Minimal, reliable setup for differential drive robots

# Robot footprint - standard differential drive setup
robot_radius: 0.35 # Conservative radius for safety

# Obstacle layer parameters - proven values
obstacle_range: 2.0
raytrace_range: 2.5

# Inflation parameters - conservative and stable
inflation_radius: 0.55
cost_scaling_factor: 5.0 # Standard scaling

# Map update parameters - balanced performance
map_type: costmap
track_unknown_space: false # Simplified - don't track unknown
unknown_cost_value: 0 # Unknown areas are free
lethal_cost_threshold: 100
neutral_cost: 50
mark_threshold: 0
clear_threshold: 0

# Transform tolerance - generous for stability
transform_tolerance: 0.5

# Observation sources - standard setup
observation_sources: scan

scan:
  {
    sensor_frame: laser,
    data_type: LaserScan,
    topic: scan,
    marking: true,
    clearing: true,
    min_obstacle_height: -2.0,
    max_obstacle_height: 2.0,
    expected_update_rate: 0.0,
    observation_persistence: 0.0,
    inf_is_valid: false,
    clear_after_reading: true,
  }
