# EKF Localization Node Configuration
# Extended Kalman Filter for GPS + odometry sensor fusion

# Publishing frequency (Hz)
frequency: 30.0

# Sensor timeout
sensor_timeout: 0.1

# Two-dimensional mode (ignore z, roll, pitch)
two_d_mode: true

# Transform time offset
transform_time_offset: 0.0

# Transform timeout
transform_timeout: 0.0

# Print diagnostics
print_diagnostics: true

# Debug mode
debug: false

# Debug output file (optional)
# debug_out_file: /tmp/ekf_debug.txt

# Map frame
map_frame: map

# Odometry frame
odom_frame: odom

# Base link frame
base_link_frame: base_link

# World frame (use odom for local navigation)
world_frame: odom

# Odometry source configuration
# odom0: GPS-based odometry from navsat_transform_node
odom0: /odometry/gps
odom0_config: [
    true,
    true,
    false, # x, y, z (use x, y; ignore z)
    false,
    false,
    false, # roll, pitch, yaw (ignore orientation from GPS)
    false,
    false,
    false, # vx, vy, vz (no velocity from GPS)
    false,
    false,
    false, # vroll, vpitch, vyaw (no angular velocity)
    false,
    false,
    false,
  ] # ax, ay, az (no acceleration)

# Differential mode (false = absolute measurements)
odom0_differential: false

# Relative mode (false = absolute coordinates)
odom0_relative: false

# Remove gravitational acceleration
odom0_pose_use_child_frame: false

# Queue size for odometry messages
odom0_queue_size: 10

# Reject outliers that are this many standard deviations from the current estimate
odom0_pose_rejection_threshold: 5.0
odom0_twist_rejection_threshold: 1.0

# IMU source configuration (if available)
# imu0: /imu
# imu0_config: [false, false, false,    # x, y, z (don't use position from IMU)
#               false, false, true,     # roll, pitch, yaw (use yaw only)
#               false, false, false,    # vx, vy, vz (don't use velocity from IMU)
#               false, false, true,     # vroll, vpitch, vyaw (use angular velocity in yaw)
#               true,  true,  true]     # ax, ay, az (use linear acceleration)

# Process noise covariance matrix
# Higher values = trust measurements less, trust model more
# Lower values = trust measurements more, trust model less
process_noise_covariance:
  [
    0.05,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0.05,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0.06,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0.03,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0.03,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0.06,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0.025,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0.025,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0.04,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0.01,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0.01,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0.02,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0.01,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0.01,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0.015,
  ]

# Initial estimate covariance matrix
# High values = very uncertain about initial state
initial_estimate_covariance:
  [
    1e-9,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-9,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-9,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-9,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-9,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-9,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-9,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-9,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-9,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-9,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-9,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-9,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-9,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-9,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1e-9,
  ]
